"""Generate Markdown, HTML, and PDF project report for GH Buddy."""

from __future__ import annotations

from pathlib import Path

try:
    import markdown
except ModuleNotFoundError:  # pragma: no cover - fallback when markdown is unavailable
    markdown = None
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import Image, PageBreak, Paragraph, SimpleDocTemplate, Spacer


REPORT_MD = Path("docs/project_report.md")
REPORT_HTML = Path("docs/project_report.html")
REPORT_PDF = Path("docs/project_report.pdf")


def md_to_basic_html(markdown_text: str) -> str:
    logo_html = ""
    logo_path = Path("logo/gh_logo.png")
    if logo_path.exists():
        logo_html = "<img src='../logo/gh_logo.png' alt='GH Buddy Logo' style='max-width:260px; margin-bottom:16px;'/>"
    if markdown is not None:
        body = markdown.markdown(markdown_text, extensions=["tables", "fenced_code"])
    else:
        body = "<pre>" + markdown_text.replace("<", "&lt;").replace(">", "&gt;") + "</pre>"
    return f"""<html>
<head>
  <meta charset='utf-8'>
  <title>GH Buddy Report</title>
  <style>
    body {{ font-family: Arial, sans-serif; max-width: 980px; margin: 32px auto; line-height: 1.5; color: #0f172a; }}
    h1,h2,h3 {{ color: #1e3a8a; }}
    table {{ border-collapse: collapse; width: 100%; margin: 12px 0; }}
    th, td {{ border: 1px solid #cbd5e1; padding: 8px; text-align: left; }}
    th {{ background: #eff6ff; }}
    code {{ background: #f1f5f9; padding: 2px 4px; }}
  </style>
</head>
<body>
  {logo_html}
  {body}
  <hr/>
  <p><strong>Print to PDF:</strong> Open this HTML in a browser and press Ctrl+P, then Save as PDF.</p>
</body>
</html>"""


def generate_pdf_from_markdown(markdown_text: str, output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    doc = SimpleDocTemplate(str(output_path), pagesize=A4, leftMargin=36, rightMargin=36, topMargin=36, bottomMargin=36)
    styles = getSampleStyleSheet()
    story = []
    logo_path = Path("logo/gh_logo.png")
    if logo_path.exists():
        story.append(Image(str(logo_path), width=200, height=105))
        story.append(Spacer(1, 24))
    story.append(Paragraph("<b>GH Buddy Chatbot</b>", styles["Title"]))
    story.append(Spacer(1, 12))
    story.append(Paragraph("University-Style Project Report", styles["Heading2"]))
    story.append(Spacer(1, 12))
    story.append(Paragraph("Generated by GH Buddy toolkit", styles["BodyText"]))
    story.append(PageBreak())

    for line in markdown_text.splitlines():
        text = line.strip()
        if not text:
            story.append(Spacer(1, 8))
            continue
        if text.startswith("# "):
            story.append(Paragraph(f"<b>{text[2:]}</b>", styles["Title"]))
        elif text.startswith("## "):
            story.append(Paragraph(f"<b>{text[3:]}</b>", styles["Heading2"]))
        elif text.startswith("### "):
            story.append(Paragraph(f"<b>{text[4:]}</b>", styles["Heading3"]))
        else:
            cleaned = text.replace("<", "&lt;").replace(">", "&gt;")
            story.append(Paragraph(cleaned, styles["BodyText"]))
        story.append(Spacer(1, 6))
    doc.build(story)


def main() -> None:
    if not REPORT_MD.exists():
        raise FileNotFoundError("docs/project_report.md not found.")
    markdown_text = REPORT_MD.read_text(encoding="utf-8")
    REPORT_HTML.write_text(md_to_basic_html(markdown_text), encoding="utf-8")
    generate_pdf_from_markdown(markdown_text, REPORT_PDF)
    print("Report generated:")
    print(f"- {REPORT_HTML}")
    print(f"- {REPORT_PDF}")


if __name__ == "__main__":
    main()
